Repository uoft-tapp/tapp, pull requests merged in 2021-04, with the labels that each got.

#477 Instructor permission test
  backend/app/controllers/api/v1/instructor/applicants_controller.rb
  backend/app/controllers/api/v1/instructor/applications_controller.rb
  backend/app/controllers/api/v1/instructor/assignments_controller.rb
  backend/app/controllers/api/v1/instructor/positions_controller.rb
  backend/app/controllers/api/v1/instructor/sessions_controller.rb
  backend/app/models/user.rb
  backend/app/serializers/user_serializer.rb
  backend/app/services/active_user_service.rb
  frontend/src/tests/api.test.js
  frontend/src/tests/instructor-permission-test.js
  frontend/src/tests/user-tests.js
Labels: javascript, test

#538 Multiple Manipulation Confirm Dialog
  frontend/src/libs/utils.ts
  frontend/src/views/admin/assignments/offer-actions.js
  frontend/src/views/admin/assignments/offer-button-with-dialog.tsx
  frontend/src/views/admin/assignments/offer-confirmation-dialog.tsx
  frontend/src/views/admin/ddahs/ddah-confirmation-dialog.tsx
  frontend/src/views/admin/ddahs/index.tsx
Labels: javascript

#559 Update README.md
  README.md
Labels: enhancement

#552 added recent activity date col for DDAH table
  frontend/src/views/admin/ddah-table/index.tsx
Labels: javascript
